project:
  type: website
  output-dir: docs
  
publish:
  gh-pages: true
  


website:
  favicon: logo_favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - app_features.qmd
      - href: impact.qmd
        text: Impact
      - href: contact.qmd
        text: Contact
        
  sidebar:
    style: docked
    background: "#609c91"
    foreground: "white"
    collapse-level: 1
    contents:

      - section: "Data & Methodology"
        contents:
          - text: "Data sources"
            href: data_and_methodology.qmd#data-sources
          - text: "Data process"
            href: data_and_methodology.qmd#data-process

      - section: "Research & Evidence"
        contents:
          - text: "Research Papers"
            href: evidence.qmd#research-publications
          - text: "Evidence & Analytics"
            href: evidence.qmd#evidence-analytics
            
      - section: "Recognition & Media"
        contents:
          - text: "Awards"
            href: media.qmd#awards
          - text: "In the news"
            href: media.qmd#news


format:
  html:
    theme: zephyr
    css: styles.css
    toc: false

editor: visual



